Project3_jahenkor_203: Project3_main_jahenkor_203.c Project3_llist_jahenkor_203.c
	gcc -v -O0 -g -o Project3_jahenkor_203 Project3_main_jahenkor_203.c Project3_llist_jahenkor_203.c -Wall
clean:
	rm -f Project3_jahenkor_203
